baseURL: "https://sample-log.vercel.app/"
title: VSC4T-HUGO
theme: VSC4T
languageCode: "zh-tw"
pagination:
  pagerSize: 10

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      hardWraps: true #换行
      unsafe: true # 允許 HTML 標籤
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

minify:
  disableXML: true
  minifyOutput: true
  
params:
  comments: true
  mainSections: posts
  ShowCodeCopyButtons: true
  showToc: true
  TocOpen: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false

  label:
    icon: /apple-touch-icon.png
    iconHeight: 35

menu:
  main:
    - identifier: archives
      name: 時間軸
      url: /archives/
      weight: 10
    - identifier: categories
      name: 分類
      url: /categories/
      weight: 20
    - identifier: tags
      name: 標籤
      url: /tags/
      weight: 30

